version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: SENHA
      POSTGRES_USER: postgres
      POSTGRES_DB: db1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
